apiVersion: v1
kind: Service
metadata:
  name: todo-service
  namespace: todo
spec:
  selector:
    app: todo-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000 
      nodePort: 30000
